### ISSUE TITLE
Special Effects Management window isn't scrollable

### ISSUE THREAD

**Issue by orangebutblue** [ghost-fvtt/fxmaster#415]
### Expected Behavior

have a scroll bar if the window size is getting too large for the screen

### Current Behavior

When you have too many entries in the special effects management window, the window expands indefinitely outside of the screen

### Steps to Reproduce

1. open effects management tab
2. expand folder with a bunch of entries

### Context

I use the wfrp4e system if that's relevant 

### Version

v3.5.2

### Foundry VTT Version

v10.291

### Operating System

Windows 11

### Browser / App

Chrome

### Game System

wfrp4e

### Relevant Modules

Jinker's Animated Art Pack

**Comment by ghost91-** [comment]
Hello @orangebutblue, sorry for the late reply, I've been a bit busy lately.

This actually seems to be an incompatibility with styling performed by wfrp4e. It seems they have special styling to adjust the FXMaster styling:
```css
/* FX MASTER STYLING */
.fxmaster .config.collapsible .flexrow strong {
  font-weight: normal;
}

#specials-config {
  max-height: fit-content;
  min-height: fit-content;
  height: fit-content !important;
}
#specials-config .window-header .close {
  position: absolute;
  top: 9px;
  left: auto;
  right: 7px;
}
#specials-config .window-content {
  *max-height: fit-content; 
  min-height: fit-content;
  padding: 7px 7px;
}
  #specials-config .window-content .directory .directory-header {
    display: none;
  }
  #specials-config .window-content .directory-list {
    max-height: fit-content;
    padding: 0px;
    margin: 0px;
  }
    #specials-config .window-content .directory-list .directory-item {
       /*     display: flex; */
       margin: 5px 0px 5px 0px;
       padding: 3px;
       background: #bb8b4326;
       box-shadow: inset 0px 0px 3px black;
       border: none;
    }
     #specials-config .window-content .directory-list .directory-item img {
      border-radius: 30px;
      box-shadow: 0px 0px 10px black;
    }
    #specials-config .window-content .directory-list .directory-item:nth-child(odd) {
      background: #69573c47;
    }
  #specials-config .window-content .directory-footer {
    display: none;
  }

/* ======================= */
```

When I remove this part of their custom styling:
```css
#specials-config {
  max-height: fit-content;
  min-height: fit-content;
  height: fit-content !important;
}
```
it goes back to normal, so without having looked into it in too much detail, I think this is the problem and should be adjusted on their side.

I'll close this issue, since it does not seem to be an issue on FXMaster's side, but on wfrp4e's side. I recommend you create an issue at their repository. Feel free to reference this issue in the new one.
